#import './UserFragment.gql'

mutation SignUp($name: String!, $email: String!, $password: String!) {
  signup(name: $name, email: $email, password: $password) {
    token
    user {
      ...UserFragment
    }
  }
}
